### PR TITLE
Ignore tar exit code 1

### PR DESCRIPTION
**Pull request by StoneLabs**
see #49.

Setting up the dev environment took me longer than expected but this should do the trick.
I've tested it by spoofing my tar command to constantly exit with 0/1/2.

~ Stone

### CODE REVIEW

**Review by itzg — APPROVED** [review]
Looks great! Thanks for providing the fix for that.

**Comment by itzg** [comment]
Hmm, I can't tell yet why the test build failed 

https://github.com/itzg/docker-mc-backup/runs/4471343315?check_suite_focus=true

Later I can look at it closer.

**Comment by StoneLabs** [comment]
I know why, my bad I'll fix it

**Review by itzg — APPROVED** [review]
Ah yes, that makes sense. That seems like a little mistake I would do too 😀

**Pull request merged**
