### PR TITLE
Update restic to latest release (0.12.1)

### LINKED ISSUE #37: Update restic to latest release
Restic 0.12.1 has been out for a couple of months now.

### PR DESCRIPTION
**Pull request by djmattyg007**
Fixes #37

### CODE REVIEW

**Review by itzg — APPROVED** [review]
Thanks!

**Comment by itzg** [comment]
Can you fix the lint errors? I had forgotten to enable the build check on your previous PR.

**Comment by djmattyg007** [comment]
Given the line with the error was there before my changes, and was unrelated to my changes, would you mind making the change? At the very least it should be handled as part of a separate PR, as the relevant change is not related to upgrading restic.

**Comment by itzg** [comment]
Good points. I'll take care of that.

**Pull request merged**
