### PR TITLE
Initial push for ARM64 Arch

### PR DESCRIPTION
**Pull request by jensenrob91**
Hey Geoff,

Just made a arm64 branch and tested on my Raspberry Pi 4. Working great! Not sure if you'd like to add this as a branch in your main repo. Thanks for all the work on this. I got to learn a lot about restic and rclone!

Changed Alpine Docker image to arm64 supported tag

Changed ARG IMAGE_ARCH to arm64

Updated software version dependencies

Changed Demoter github release url to reflect newer naming conventions

### CODE REVIEW

**Comment by itzg** [comment]
Great idea. Try switching the PR to point at the new branch https://github.com/itzg/docker-mc-backup/tree/arm64

**Comment by jensenrob91** [comment]
Alright , I think I did it!

**Comment by itzg** [comment]
(Side note to self, should really fix the existing code to make linting happy.)

**Comment by itzg** [comment]
Can you follow up with a PR on master to just bump the versions to match?

**Review by itzg — APPROVED** [review]

**Comment by jensenrob91** [comment]
Yessir! I'll git , heh, right on it.

**Comment by itzg** [comment]
...and bear with me, I might end up combining the "two branches" into one and switching to [this github action](https://github.com/marketplace/actions/docker-setup-buildx) to do a multiarch build. I forgot that a typical linux amd64 build server won't build arm64 without some extra steps anyway. In the meantime, you (and others) can now easily git pull and docker build an image for arm64.

**Comment by jensenrob91** [comment]
No problem at all, that would be awesome actually. My thoughts exactly , I figured others could get the arm64 branch while you work on the multi-arch. Thanks for making it possible, hope I contributed in a good way! New to all this so still learning the ropes. :)

**Comment by itzg** [comment]
You did great!

**Pull request merged**
